### ISSUE TITLE
futurized version hpx sort segfaults when compiled with clang with 2 or more hpx:threads

### ISSUE THREAD

**Issue by pagrubel** [STEllAR-GROUP/inncabs#2]
export INNCABS_LAUNCH_TYPES=async
export INNCABS_TIMES_OUTPUT=true
export INNCABS_MIN_OUTPUT=true
export INNCABS_REPEATS=2

/home/pagrubel/build_inncabs_hpx_futurized/clang_build/sort/sort --hpx:threads 2 --hpx:bind balanced 100000000 8192 2048 128
{stack-trace}: 4 frames:
0x2aaaadde6136  : hpx::util::stack_trace::trace(void**, unsigned long) + 0x6 in /home/pagrubel/build/hpx_buildrelease_clang/lib/libhpx.so.0
0x2aaaad86ac15  : hpx::termination_handler(int) + 0x315 in /home/pagrubel/build/hpx_buildrelease_clang/lib/libhpx.so.0
0x2aaaabcb58d0  : ??? + 0x2aaaabcb58d0 in /lib/x86_64-linux-gnu/libpthread.so.0
0x2aaab3d7c0ab  : ???
{what}: Illegal instruction
{config}:
  HPX_HAVE_NATIVE_TLS=ON
  HPX_HAVE_STACKTRACES=ON
  HPX_HAVE_COMPRESSION_BZIP2=OFF
  HPX_HAVE_COMPRESSION_SNAPPY=OFF
  HPX_HAVE_COMPRESSION_ZLIB=OFF
  HPX_HAVE_PARCEL_COALESCING=ON
  HPX_HAVE_PARCELPORT_TCP=ON
  HPX_HAVE_PARCELPORT_MPI=OFF
  HPX_HAVE_PARCELPORT_IPC=OFF
  HPX_HAVE_PARCELPORT_IBVERBS=OFF
  HPX_HAVE_VERIFY_LOCKS=OFF
  HPX_HAVE_HWLOC=ON
  HPX_HAVE_ITTNOTIFY=OFF
  HPX_HAVE_RUN_MAIN_EVERYWHERE=OFF
  HPX_LIMIT=5
  HPX_PARCEL_MAX_CONNECTIONS=512
  HPX_PARCEL_MAX_CONNECTIONS_PER_LOCALITY=4
  HPX_INITIAL_AGAS_LOCAL_CACHE_SIZE=256
  HPX_AGAS_LOCAL_CACHE_SIZE_PER_THREAD=32
  HPX_HAVE_MALLOC=tcmalloc
  HPX_PREFIX (configured)=/home/pagrubel/build/hpx_buildrelease_clang
  HPX_PREFIX=/home/pagrubel/build/hpx_buildrelease_clang
{version}: V0.9.11-trunk (AGAS: V3.0), Git: be2ee627b5
{boost}: V1.56.0
{build-type}: release
{date}: Jul  9 2015 00:10:26
{platform}: linux
{compiler}: Clang version 3.4.2 (tags/RELEASE_34/dot2-final)
{stdlib}: GNU libstdc++ version 20140908
Aborted

**Comment by hkaiser** [comment]
That should be fixed now, please try again.

**Comment by pagrubel** [comment]
Will try

**Comment by pagrubel** [comment]
@hkaiser  
No, I'm still getting the same error and it happens for odd number of repeats too!
